### ISSUE TITLE
TODO for v2 Release

### ISSUE THREAD

**Issue by keithamus** [chaijs/loupe#15]
Here's a short list of things we'll probably need to do to get this ready for publishing:

## Bare Minimum
 - [x] get `npm t` passing locally (fails on safari for me)
 - [x] Get CI passing (fails on ~~lint check it seems~~ now fails on saucelabs)
 - [ ] Totally rewrite the readme so it makes more sense.

## Probably should do:
 - [x] Update all deps/devdeps so we're in a good clean state

## Would be really nice to have
 - [x] Migrate to github actions and drop travis ci
 - [x] Separate lint check in GH Actions
 - [x] Separate node/browser tests in GH actions

## Stretch goals
 - [x] Migrate commitlint to github actions
 - [x] Migrate codecov to github actions checks

**Comment by pcorpet** [comment]
Hi there, is anything missing for v2?

**Comment by pcorpet** [comment]
@keithamus @flaambe need any help for a v2 release? It seems that everything's ready

**Comment by flaambe** [comment]
@pcorpet Hi. It would be better, if @keithamus has time to outline the next steps. I thought the main goal of v2 release is to bring it to chai.

**Comment by keithamus** [comment]
The goal of a v2 release is indeed to fold it into Chai. I've been quite burnt out recently on the Chai project, I've been struggling to be motivated to do anything on it.

Having said that I just went ahead and published this to npm as `2.0.0`. If someone would like to make a PR to chai with the upgrade and we can look to merging it and see what needs to happen to chai to cut a release. Also if someone would be kind enough to prepare some release notes for the 2.0.0 release of this package I can put them into the release notes which I'm sure others will hugely appreciate.
